// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package service2;

public final class NoiseMonitorServiceImpl {
  private NoiseMonitorServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_NoiseMonitorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_NoiseMonitorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_NoiseMonitorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_NoiseMonitorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service2.proto\022\010service2\"%\n\023NoiseMonit" +
      "orRequest\022\016\n\006number\030\001 \001(\003\"<\n\024NoiseMonito" +
      "rResponse\022\023\n\013noisyValues\030\001 \001(\t\022\017\n\007averag" +
      "e\030\002 \001(\0012h\n\023NoiseMonitorService\022Q\n\014NoiseM" +
      "onitor\022\035.service2.NoiseMonitorRequest\032\036." +
      "service2.NoiseMonitorResponse\"\000(\001B%\n\010ser" +
      "vice2B\027NoiseMonitorServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service2_NoiseMonitorRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service2_NoiseMonitorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_NoiseMonitorRequest_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_service2_NoiseMonitorResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service2_NoiseMonitorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_NoiseMonitorResponse_descriptor,
        new java.lang.String[] { "NoisyValues", "Average", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
