// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package service2;

public interface NoiseMonitorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.NoiseMonitorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 number = 1;</code>
   */
  long getNumber();
}
