// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package service2;

public interface NoiseMonitorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.NoiseMonitorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string noisyValues = 1;</code>
   */
  java.lang.String getNoisyValues();
  /**
   * <code>string noisyValues = 1;</code>
   */
  com.google.protobuf.ByteString
      getNoisyValuesBytes();

  /**
   * <code>double average = 2;</code>
   */
  double getAverage();
}
