// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package service3;

public interface SnoreMeterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.SnoreMeterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string snoreAlert = 1;</code>
   */
  java.lang.String getSnoreAlert();
  /**
   * <code>string snoreAlert = 1;</code>
   */
  com.google.protobuf.ByteString
      getSnoreAlertBytes();
}
