// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package service3;

public interface SnoreMeterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.SnoreMeterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   */
  int getNumber();
}
