// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package service1;

public final class SleepPatternServiceImpl {
  private SleepPatternServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_SleepPatternRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_SleepPatternRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_SleepPatternResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_SleepPatternResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_WeeklySleepPatternRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_WeeklySleepPatternRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_WeeklySleepPatternResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_WeeklySleepPatternResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service1.proto\022\010service1\"\'\n\023SleepPatte" +
      "rnRequest\022\020\n\010userName\030\001 \001(\t\"\261\001\n\024SleepPat" +
      "ternResponse\022\020\n\010userName\030\001 \001(\t\0227\n\007patter" +
      "n\030\002 \001(\0162&.service1.SleepPatternResponse." +
      "Pattern\"N\n\007Pattern\022\013\n\007UNKNOWN\020\000\022\r\n\tVERY_" +
      "WELL\020\001\022\010\n\004WELL\020\002\022\014\n\010NOT_WELL\020\003\022\017\n\013VERY_U" +
      "NWELL\020\004\"-\n\031WeeklySleepPatternRequest\022\020\n\010" +
      "userName\030\001 \001(\t\"\275\001\n\032WeeklySleepPatternRes" +
      "ponse\022\020\n\010userName\030\001 \001(\t\022=\n\007pattern\030\002 \001(\016" +
      "2,.service1.WeeklySleepPatternResponse.P" +
      "attern\"N\n\007Pattern\022\013\n\007UNKNOWN\020\000\022\r\n\tVERY_W" +
      "ELL\020\001\022\010\n\004WELL\020\002\022\014\n\010NOT_WELL\020\003\022\017\n\013VERY_UN" +
      "WELL\020\0042\313\001\n\023SleepPatternService\022O\n\014SleepP" +
      "attern\022\035.service1.SleepPatternRequest\032\036." +
      "service1.SleepPatternResponse\"\000\022c\n\022Weekl" +
      "ySleepPattern\022#.service1.WeeklySleepPatt" +
      "ernRequest\032$.service1.WeeklySleepPattern" +
      "Response\"\0000\001B%\n\010service1B\027SleepPatternSe" +
      "rviceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service1_SleepPatternRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1_SleepPatternRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_SleepPatternRequest_descriptor,
        new java.lang.String[] { "UserName", });
    internal_static_service1_SleepPatternResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1_SleepPatternResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_SleepPatternResponse_descriptor,
        new java.lang.String[] { "UserName", "Pattern", });
    internal_static_service1_WeeklySleepPatternRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service1_WeeklySleepPatternRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_WeeklySleepPatternRequest_descriptor,
        new java.lang.String[] { "UserName", });
    internal_static_service1_WeeklySleepPatternResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service1_WeeklySleepPatternResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_WeeklySleepPatternResponse_descriptor,
        new java.lang.String[] { "UserName", "Pattern", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
