// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package service1;

public interface WeeklySleepPatternRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.WeeklySleepPatternRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();
}
